{{~def 'prjId' (asJavaId ghProjectId)~}}
{{#each modules}}
--- !!org.boothub.context.SourceContext
artifact: {{artifact}}
fileContexts:
    - !!org.boothub.context.SourceFileContext
      fileName: Plugin.groovy
      targetBaseDir: src/main/groovy
      targetPackage: {{basePackage}}
      targetFileClass: {{pluginClassName}}

    - !!org.boothub.context.SourceFileContext
      fileName: PluginExtension.groovy
      targetBaseDir: src/main/groovy
      targetPackage: {{basePackage}}
      targetFileClass: {{pluginClassName}}Extension

    - !!org.boothub.context.SourceFileContext
      fileName: Task.groovy
      targetBaseDir: src/main/groovy
      targetPackage: {{basePackage}}
      targetFileClass: {{taskClassName}}

    - !!org.boothub.context.SourceFileContext
      fileName: TaskImpl.groovy
      targetBaseDir: src/main/groovy
      targetPackage: {{basePackage}}.impl
      targetFileClass: {{taskClassName}}Impl

    - !!org.boothub.context.SourceFileContext
      fileName: PluginSpec.groovy
      targetBaseDir: src/test/groovy
      targetPackage: {{basePackage}}
      targetFileClass: {{pluginClassName}}Spec

    - !!org.boothub.context.SourceFileContext
      fileName: TaskSpec.groovy
      targetBaseDir: src/test/groovy
      targetPackage: {{basePackage}}
      targetFileClass: {{taskClassName}}Spec
{{/each}}
